### ISSUE TITLE
aoflagger coredump

### ISSUE THREAD

**Issue by o-smirnov** [radio-astro-debian/aoflagger-debian#3]
```
blecher@jake:~/real_data_comparision$ aoflagger 3C279_selfcal.MS
AOFlagger 2.7.1 (2015-07-01) command line application
This program will execute an RFI strategy as can be created with the RFI gui
and executes it on one or several observations.

Author: André Offringa (offringa@gmail.com)

Starting strategy on 2015-Oct-01 11:24:07.290824
Illegal instruction (core dumped)
```

Debugger suggests it's in some legitimate C++ code:

```
0x000000000048c3f0 in ConsoleProgressHandler::OnStartTask(rfiStrategy::Action const&, unsigned long, unsigned long, std::string const&, unsigned long) ()
```

But, illegal instruction? Did something go wrong with the package build? @aroffringa?

**Comment by aroffringa** [comment]
I think this implies that the binaries are build with a machine different from the machine you are using it on, while the compiling machine has cpu instructions (e.g. AVX2) that your machine doesn't understand. By default, the CMakeLists.txt adds "-march=native", which causes the behaviour that binaries are not compatible amongst different machines. The package builder should probably remove this option or specify a more specific target cpu. (Note that leaving out -march=native completely slows the execution speed somewhat -- that's why it's there by default).

**Comment by o-smirnov** [comment]
Yeah that makes sense. This may be a case where it makes sense to actually ship different binary versions, if you're getting substantial benefit from something like AVX2 when available (this the case for wsclean as well I imagine?).

@gijzelaerr is there a straightforward way to ship such architecture-specific binaries in the deb packaging system?

**Comment by gijzelaerr** [comment]
not sure. We can probably only build binaries with CPU instruction support
up to the ones available on the ubuntu build farm.

2015-10-01 15:02 GMT+02:00 Oleg Smirnov notifications@github.com:

> Yeah that makes sense. This may be a case where it makes sense to actually
> ship different binary versions, if you're getting substantial benefit from
> something like AVX2 when available (this the case for wsclean as well I
> imagine?).
> 
> @gijzelaerr https://github.com/gijzelaerr is there a straightforward
> way to ship such architecture-specific binaries in the deb packaging system?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/radio-astro-debian/aoflagger-debian/issues/3#issuecomment-144720384
> .

## 

Gijs Molenaar
http://pythonic.nl

**Comment by o-smirnov** [comment]
OK, well in any case the current deb is broken on e.g. jake and elwood. So @gijzelaerr needs to rebuild a generic version of the package without "-march=native" asap, and then we can figure out if we can build architecture-dependent ones.

**Comment by gijzelaerr** [comment]
will see what I can do, but quite busy rounding stuff up here since I'm coming to SA in a couple of days.

**Comment by gijzelaerr** [comment]
https://launchpadlibrarian.net/218279306/buildlog_ubuntu-trusty-amd64.aoflagger_2.7.1-1trustry_BUILDING.txt.gz

Yes, I can see `-march=native` in the logs, probably this stuff is build on a machine with AVX2 support.

Jake has no support for this:

```
 cat /proc/cpuinfo | grep flags |uniq
flags       : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf eagerfpu pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer aes xsave avx lahf_lm ida arat xsaveopt pln pts dtherm tpr_shadow vnmi flexpriority ept vpid
```

I will compile packages forced to first intel 64 bit arch, which implies some registers, but may leave out some of the more fancy SIMD instruction sets.

**Comment by gijzelaerr** [comment]
I've updated the package in the PPA and Alexander Akoto-Danso has reported that this fixes his problems.
